### ISSUE TITLE
Add feature: generate random token

### ISSUE THREAD

**Issue by saeedhosan** [appsaeed/utilies#2]
### Generate random token 
We will add **generateToken** function to the package, when we need to generate a token we will be able to easily generate a string token for our project
<br>
code snippets:

````ts
export function generateToken(length: number = 30): string {
    const token = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
    let a: string[] = token.split("");
    let b: number | string[] = [];
    let rand: number;
    for (let i = 0; i < length; i++) {
      rand = Number((Math.random() * (a.length - 1)).toFixed(0));
      b[i] = a[rand];
    }
    return b.join("");
  }
````

#### The function should be included in the generate.ts file

**Comment by appsaeed** [comment]
complete to add generateToken 
update log <br>
[https://github.com/appsaeed/utilies/commit/1ebb9490b2f48fbc7f7c7c59fdc77aa9d97e8547#diff-0e9ffa40772b7eca15b8e9fed0a847258c6a80dca2f41d5ddc0cb70357736f2c](https://github.com/appsaeed/utilies/commit/1ebb9490b2f48fbc7f7c7c59fdc77aa9d97e8547#diff-0e9ffa40772b7eca15b8e9fed0a847258c6a80dca2f41d5ddc0cb70357736f2c)
